// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCRM.Data;

namespace WebCRM.Data.Migrations
{
    [DbContext(typeof(CRMDBContext))]
    [Migration("20210806155850_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("WebCRM.Data.AccountMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimaryAccountMember")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MembershipCreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MembershipCreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MembershipRemovalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipRemovedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountID", "MemberID");

                    b.ToTable("AccountMembership");
                });

            modelBuilder.Entity("WebCRM.Data.AccountNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NoteCreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NoteRemovalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteRemovedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountID");

                    b.ToTable("AccountNote");
                });

            modelBuilder.Entity("WebCRM.Data.CRMAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AccountRetirementDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CRMAccount");
                });

            modelBuilder.Entity("WebCRM.Data.Contract", b =>
                {
                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClosedBy")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ContractAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ContractCloseDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ContractStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPaymentRecievedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OriginalContractID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPaidAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountID", "MemberID");

                    b.HasIndex("AccountID", "MemberID");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("WebCRM.Data.ContractExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("ContractID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExpenseAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpenseCancelDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpenseCanceledBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpenseEnteredBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpenseEnteredDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractID");

                    b.ToTable("ContractExpense");
                });

            modelBuilder.Entity("WebCRM.Data.ContractTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TransactionCancelDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionCanceledBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionEnteredBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionEnteredDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractID");

                    b.ToTable("ContractTransaction");
                });

            modelBuilder.Entity("WebCRM.Data.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemberAddedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MemberAddedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MemberRemovalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberRemovedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("WebCRM.Data.MemberTestimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastedUpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestimonialClipEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestimonialClipStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestimonialRemovedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TestimonialRemovedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestimonialText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberID");

                    b.ToTable("MemberTestimonial");
                });
#pragma warning restore 612, 618
        }
    }
}
